@startuml catalogo
class Videojuego {
    long id
    String nombre
    float precio
    int categoriaId_FK
}
class Consola {
    long id
    String nombre
}
class Categoria {
    long id
    String nombre
    int estado
}

Categoria "1" --- "*" Videojuego
@enduml